=== pehovorka/smartelefon/eshop.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    xmlns:sch="http://purl.oclc.org/dsdl/schematron" elementFormDefault="qualified"
    xmlns="https://petrhovorka.com/smartelefon"
    targetNamespace="https://petrhovorka.com/smartelefon" vc:minVersion="1.1"
    xpathDefaultNamespace="https://petrhovorka.com/smartelefon">
    <xs:annotation>
        <xs:appinfo>
            <sch:ns uri="https://petrhovorka.com/smartelefon" prefix="q"/>
        </xs:appinfo>
    </xs:annotation>
    <xs:element name="eshop" type="eshopType">
        <xs:annotation>
            <xs:appinfo>
                <sch:pattern>
                    <sch:title>Kontrola cen</sch:title>
                    <sch:rule context="q:eshop/q:polozky/q:polozka">
                        <sch:assert
                            test="sum(q:cena[@typ = 'puvodni'][@mena = 'CZK']) &gt;= sum(q:cena[@typ = 'aktualni'][@mena = 'CZK'])"
                            >Aktuální cena musí být stejná, nebo nižší, než původní
                            (CZK)!</sch:assert>
                        <sch:assert
                            test="sum(q:cena[@typ = 'puvodni'][@mena = 'EUR']) &gt;= sum(q:cena[@typ = 'aktualni'][@mena = 'EUR'])"
                            >Aktuální cena musí být stejná, nebo nižší, než původní
                            (EUR)!</sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>
        <xs:unique name="unikatnostProduktovychCisel">
            <xs:selector xpath="polozky/polozka/produktoveCislo"/>
            <xs:field xpath="."/>
        </xs:unique>
    </xs:element>
    <xs:complexType name="eshopType">
        <xs:sequence>
            <xs:element name="polozky" type="polozkyType" maxOccurs="1"/>
            <xs:element name="dph" type="dphType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="polozkyType">
        <xs:sequence>
            <xs:element name="polozka" type="polozkaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="dphType">
        <xs:restriction base="kladnaDesetinnaType"/>
    </xs:simpleType>
    <xs:complexType name="polozkaType">
        <xs:sequence>
            <xs:element name="vyrobce" type="vyrobceType"/>
            <xs:element name="model" type="modelType"/>
            <xs:element name="produktoveCislo" type="produktoveCisloType"/>
            <xs:element name="cena" type="cenaType" minOccurs="4" maxOccurs="4"/>
            <xs:element name="dostupnost" type="dostupnostType"/>
            <xs:element name="obrazek" type="obrazekType"/>
            <xs:element name="video" type="videoType" minOccurs="0"/>
            <xs:element name="popis" type="popisType"/>
            <xs:element name="parametry" type="parametryType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="parametryType">
        <xs:sequence>
            <xs:element name="system" type="systemType"/>
            <xs:element name="ram" type="ramType"/>
            <xs:element name="interniUloziste" type="interniUlozisteType"/>
            <xs:element name="externiUloziste" type="externiUlozisteType" minOccurs="0"/>
            <xs:element name="cpu" type="cpuType"/>
            <xs:element name="fotoaparat" type="fotoaparatType" minOccurs="2" maxOccurs="unbounded"/>
            <xs:element name="displej" type="displejType"/>
            <xs:element name="baterie" type="baterieType"/>
            <xs:element name="sim" type="simType"/>
            <xs:element name="konektivita" type="konektivitaType"/>
            <xs:element name="barvy" type="barvyType"/>
            <xs:element name="rozmery" type="rozmeryType"/>
            <xs:element name="obsahBaleni" type="obsahBaleniType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="vyrobceType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="modelType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="produktoveCisloType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="cenaType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="typ" type="typCenyType" use="required"/>
                <xs:attribute name="mena" type="menaType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="typCenyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="puvodni"/>
            <xs:enumeration value="aktualni"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="menaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CZK"/>
            <xs:enumeration value="EUR"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="dostupnostType">
        <xs:sequence>
            <xs:element name="sklad" type="skladType" maxOccurs="3"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="skladType">
        <xs:simpleContent>
            <xs:extension base="kladnaCelaSNulouType">
                <xs:attribute name="mesto" type="mestoType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="mestoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Praha"/>
            <xs:enumeration value="Brno"/>
            <xs:enumeration value="Ostrava"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="obrazekType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="videoType">
        <xs:restriction base="xs:string">
            <xs:pattern value="http://youtu.be.+"/>
            <xs:pattern value="https://youtu.be.+"/>
            <xs:pattern value="http://www.youtube.com/watch.+"/>
            <xs:pattern value="https://www.youtube.com/watch.+"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="popisType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="systemType">
        <xs:sequence>
            <xs:element name="nazev" type="systemNazevType" maxOccurs="1"/>
            <xs:element name="verze" type="systemVerzeType" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="systemNazevType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Android"/>
            <xs:enumeration value="iOS"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="systemVerzeType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="ramType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="jednotka" type="jednotkaUlozisteType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="jednotkaUlozisteType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TB"/>
            <xs:enumeration value="GB"/>
            <xs:enumeration value="MB"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="interniUlozisteType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="jednotka" type="jednotkaUlozisteType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="externiUlozisteType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="cpuType">
        <xs:sequence>
            <xs:element name="nazev" type="cpuNazevType"/>
            <xs:element name="pocetJader" type="pocetJaderType"/>
            <xs:element name="frekvence" type="frekvenceType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="cpuNazevType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="pocetJaderType">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>
    <xs:complexType name="frekvenceType">
        <xs:simpleContent>
            <xs:extension base="kladnaDesetinnaType">
                <xs:attribute name="jednotka" type="jednotkaFrekvenceType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="jednotkaFrekvenceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GHz"/>
            <xs:enumeration value="MHz"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="fotoaparatType">
        <xs:sequence>
            <xs:element name="rozliseni" type="rozliseniFotoaparatuType"/>
            <xs:element name="svetelnost" type="svetelnostType" minOccurs="0"/>
            <xs:element name="blesk" type="bleskType" minOccurs="0"/>
            <xs:element name="stabilizace" type="stabilizaceType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typFotoaparatuType" use="required"/>
    </xs:complexType>
    <xs:simpleType name="rozliseniFotoaparatuType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="svetelnostType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="bleskType">
        <xs:restriction base="anoNeType"/>
    </xs:simpleType>
    <xs:simpleType name="stabilizaceType">
        <xs:restriction base="anoNeType"/>
    </xs:simpleType>
    <xs:simpleType name="typFotoaparatuType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="predni"/>
            <xs:enumeration value="zadni"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="displejType">
        <xs:sequence>
            <xs:element name="velikost" type="velikostDisplejeType"/>
            <xs:element name="rozliseni" type="rozliseniDisplejeType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="velikostDisplejeType">
        <xs:simpleContent>
            <xs:extension base="kladnaDesetinnaType">
                <xs:attribute name="jednotka" type="jednotkaVelikostDisplejeType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="jednotkaVelikostDisplejeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="&quot;"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="rozliseniDisplejeType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="baterieType">
        <xs:sequence>
            <xs:element name="kapacita" type="kapacitaBaterieType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="kapacitaBaterieType">
        <xs:simpleContent>
            <xs:extension base="kladnaDesetinnaType">
                <xs:attribute name="jednotka" type="jednotkaBaterieType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:simpleType name="jednotkaBaterieType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mAh"/>
            <xs:enumeration value="Ah"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="simType">
        <xs:sequence>
            <xs:element name="pocet" type="pocetSimType"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typSimType" use="required"/>
    </xs:complexType>
    <xs:simpleType name="pocetSimType">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>
    <xs:simpleType name="typSimType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="nano"/>
            <xs:enumeration value="micro"/>
            <xs:enumeration value="mini"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="konektivitaType">
        <xs:sequence>
            <xs:element name="wifi" type="anoNeType"/>
            <xs:element name="lte" type="anoNeType"/>
            <xs:element name="bluetooth" type="anoNeType"/>
            <xs:element name="nfc" type="anoNeType"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="barvyType">
        <xs:sequence>
            <xs:element name="barva" type="barvaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="barvaType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:complexType name="rozmeryType">
        <xs:sequence>
            <xs:element name="s" type="rozmeryVelikostiType"/>
            <xs:element name="v" type="rozmeryVelikostiType"/>
            <xs:element name="h" type="rozmeryVelikostiType"/>
        </xs:sequence>
        <xs:attribute name="jednotka" type="jednotkaRozmeruTelefonuType" use="required"/>
    </xs:complexType>
    <xs:simpleType name="jednotkaRozmeruTelefonuType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mm"/>
            <xs:enumeration value="cm"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="rozmeryVelikostiType">
        <xs:restriction base="kladnaDesetinnaType"/>
    </xs:simpleType>
    <xs:complexType name="obsahBaleniType">
        <xs:sequence>
            <xs:element name="polozka" type="obsahBaleniPolozkaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="obsahBaleniPolozkaType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    <xs:simpleType name="kladnaDesetinnaType">
        <xs:restriction base="xs:decimal">
            <xs:minExclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="kladnaCelaSNulouType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="anoNeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ano"/>
            <xs:enumeration value="Ano"/>
            <xs:enumeration value="ANO"/>
            <xs:enumeration value="ne"/>
            <xs:enumeration value="Ne"/>
            <xs:enumeration value="NE"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== pehovorka/smartelefon/eshop.xml
<?xml version="1.0" encoding="UTF-8"?>
<eshop xmlns="https://petrhovorka.com/smartelefon"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://petrhovorka.com/smartelefon eshop.xsd">
    <polozky>
        <polozka>
            <vyrobce>Samsung</vyrobce>
            <model>Galaxy J5 Duos</model>
            <produktoveCislo>SM-J530FZKDETL</produktoveCislo>
            <cena typ="aktualni" mena="CZK">4790</cena>
            <cena typ="puvodni" mena="CZK">6690</cena>
            <cena typ="puvodni" mena="EUR">280</cena>
            <cena typ="aktualni" mena="EUR">200</cena>
            <dostupnost>
                <sklad mesto="Praha">0</sklad>
                <sklad mesto="Brno">0</sklad>
                <sklad mesto="Ostrava">0</sklad>
            </dostupnost>
            <obrazek>samsungJ5Duos.jpg</obrazek>
            <popis>Kromě svých vynikajících technických parametrů a množství praktických funkcí vás
                chytrý telefon Galaxy J5 od společnosti Samsung nadchne i stylovým designem. Jeho
                kovové provedení vás okouzlí na první pohled, zároveň oceníte jeho ergonomickou a
                pevnou konstrukci. A na 5,2palcovém Super AMOLED displeji s HD rozlišením, který
                chrání tvrzené 2.5D sklo, si vychutnáte veškerý multimediální obsah ve vysoké
                kvalitě.</popis>
            <parametry>
                <system>
                    <nazev>Android</nazev>
                    <verze>7.1</verze>
                </system>
                <ram jednotka="GB">2</ram>
                <interniUloziste jednotka="GB">16</interniUloziste>
                <externiUloziste>MicroSDXC</externiUloziste>
                <cpu>
                    <nazev>Exynos 7870 Octa Core 64bit</nazev>
                    <pocetJader>8</pocetJader>
                    <frekvence jednotka="GHz">1.6</frekvence>
                </cpu>
                <fotoaparat typ="zadni">
                    <rozliseni>13MPx</rozliseni>
                    <svetelnost>F/1.9</svetelnost>
                    <blesk>ano</blesk>
                    <stabilizace>ne</stabilizace>
                </fotoaparat>
                <fotoaparat typ="predni">
                    <rozliseni>13MPx</rozliseni>
                    <svetelnost>F/1.9</svetelnost>
                </fotoaparat>
                <displej>
                    <velikost jednotka="&quot;">5.2</velikost>
                    <rozliseni>1280x720</rozliseni>
                </displej>
                <baterie>
                    <kapacita jednotka="mAh">3000</kapacita>
                </baterie>
                <sim typ="nano">
                    <pocet>2</pocet>
                </sim>
                <konektivita>
                    <wifi>ano</wifi>
                    <lte>ano</lte>
                    <bluetooth>ano</bluetooth>
                    <nfc>ano</nfc>
                </konektivita>
                <barvy>
                    <barva>Černá</barva>
                    <barva>Zlatá</barva>
                    <barva>Modrá</barva>
                </barvy>
                <rozmery jednotka="mm">
                    <s>71.3</s>
                    <v>146.3</v>
                    <h>7.9</h>
                </rozmery>
                <obsahBaleni>
                    <polozka>Napájecí adaptér</polozka>
                    <polozka>USB kabel</polozka>
                    <polozka>Sluchátka</polozka>
                </obsahBaleni>
            </parametry>
        </polozka>
        <polozka>
            <vyrobce>Apple</vyrobce>
            <model>iPhone SE 32GB</model>
            <produktoveCislo>MP822CS/A</produktoveCislo>
            <cena typ="aktualni" mena="CZK">7777</cena>
            <cena typ="puvodni" mena="CZK">12999</cena>
            <cena typ="aktualni" mena="EUR">300</cena>
            <cena typ="puvodni" mena="EUR">510</cena>
            <dostupnost>
                <sklad mesto="Praha">12</sklad>
                <sklad mesto="Brno">9</sklad>
                <sklad mesto="Ostrava">4</sklad>
            </dostupnost>
            <obrazek>iPhoneSE.jpg</obrazek>
            <popis>Návrat oblíbeného designu se 4" úhlopříčkou.
                Společnost Apple opět útočí na základní smysly mnoha miliónů uživatelů po celém světě. Nový iPhone SE je totiž ideální volba pro všechny zákazníky, kteří milují malé telefony pro jejich kompaktnost a snadné ovládání jednou rukou. V oblíbeném designu tak najdete ten vůbec nejvýkonnější 4palcový telefon na světě.
            </popis>
            <parametry>
                <system>
                    <nazev>iOS</nazev>
                    <verze>11.3.1</verze>
                </system>
                <ram jednotka="GB">2</ram>
                <interniUloziste jednotka="GB">32</interniUloziste>
                <cpu>
                    <nazev>Apple A9</nazev>
                    <pocetJader>2</pocetJader>
                    <frekvence jednotka="GHz">1.84</frekvence>
                </cpu>
                <fotoaparat typ="zadni">
                    <rozliseni>12Mpx</rozliseni>
                    <svetelnost>f/2,2</svetelnost>
                    <blesk>ano</blesk>
                    <stabilizace>ne</stabilizace>
                </fotoaparat>
                <fotoaparat typ="predni">
                    <rozliseni>1,2Mpx</rozliseni>
                </fotoaparat>
                <displej>
                    <velikost jednotka="&quot;">4</velikost>
                    <rozliseni>1136x640</rozliseni>
                </displej>
                <baterie>
                    <kapacita jednotka="mAh">1624</kapacita>
                </baterie>
                <sim typ="nano">
                    <pocet>1</pocet>
                </sim>
                <konektivita>
                    <wifi>ano</wifi>
                    <lte>ano</lte>
                    <bluetooth>ano</bluetooth>
                    <nfc>ano</nfc>
                </konektivita>
                <barvy>
                    <barva>Stříbrná</barva>
                    <barva>Zlatá</barva>
                    <barva>Vesmírně šedá</barva>
                    <barva>Růžově zlatá</barva>
                </barvy>
                <rozmery jednotka="mm">
                    <s>58.6</s>
                    <v>123.8</v>
                    <h>7.6</h>
                </rozmery>
                <obsahBaleni>
                    <polozka>Manuál</polozka>
                    <polozka>USB kabel</polozka>
                    <polozka>napájecí adaptér</polozka>
                    <polozka>sluchátka</polozka>
                </obsahBaleni>
            </parametry>
        </polozka>
        <polozka>
            <vyrobce>Apple</vyrobce>
            <model>iPhone X 64GB</model>
            <produktoveCislo>MQAD2CN/A</produktoveCislo>
            <cena typ="aktualni" mena="CZK">29890</cena>
            <cena typ="puvodni" mena="CZK">29990</cena>
            <cena typ="aktualni" mena="EUR">1175</cena>
            <cena typ="puvodni" mena="EUR">1180</cena>
            <dostupnost>
                <sklad mesto="Praha">6</sklad>
                <sklad mesto="Brno">8</sklad>
                <sklad mesto="Ostrava">1</sklad>
            </dostupnost>
            <obrazek>iPhoneX.jpg</obrazek>
            <video>https://youtu.be/mW6hFttt_KE</video>
            <popis>
                iPhone jsme si vždycky představovali jako zařízení, které je vlastně jen obrazovka. Které ustoupí tomu, co na něm zrovna děláš. A které je tak inteligentní, že reaguje na dotyky, slova i pohledy. S iPhonem X jsme tuhle představu proměnili v realitu. Takhle vypadá budoucnost.
            </popis>
            <parametry>
                <system>
                    <nazev>iOS</nazev>
                    <verze>11.3.1</verze>
                </system>
                <ram jednotka="GB">3</ram>
                <interniUloziste jednotka="GB">64</interniUloziste>
                <cpu>
                    <nazev>Apple A11 Bionic Hexa Core 64bit</nazev>
                    <pocetJader>6</pocetJader>
                    <frekvence jednotka="GHz">2.5</frekvence>
                </cpu>
                <fotoaparat typ="zadni">
                    <rozliseni>12Mpx</rozliseni>
                    <svetelnost>f/1,8</svetelnost>
                    <blesk>ano</blesk>
                    <stabilizace>ano</stabilizace>
                </fotoaparat>
                <fotoaparat typ="predni">
                    <rozliseni>7Mpx</rozliseni>
                </fotoaparat>
                <displej>
                    <velikost jednotka="&quot;">5.8</velikost>
                    <rozliseni>2436x1125</rozliseni>
                </displej>
                <baterie>
                    <kapacita jednotka="mAh">2716</kapacita>
                </baterie>
                <sim typ="nano">
                    <pocet>1</pocet>
                </sim>
                <konektivita>
                    <wifi>ano</wifi>
                    <lte>ano</lte>
                    <bluetooth>ano</bluetooth>
                    <nfc>ano</nfc>
                </konektivita>
                <barvy>
                    <barva>Stříbrná</barva>
                    <barva>Vesmírně šedá</barva>
                </barvy>
                <rozmery jednotka="mm">
                    <s>70.9</s>
                    <v>143.6</v>
                    <h>7.7</h>
                </rozmery>
                <obsahBaleni>
                    <polozka>Manuál</polozka>
                    <polozka>USB kabel</polozka>
                    <polozka>napájecí adaptér</polozka>
                    <polozka>sluchátka</polozka>
                </obsahBaleni>
            </parametry>
        </polozka>
        <polozka>
            <vyrobce>Apple</vyrobce>
            <model>iPhone 8 64GB</model>
            <produktoveCislo>MQ6G2CN/A</produktoveCislo>
            <cena typ="aktualni" mena="CZK">20990</cena>
